name: release-ci
on:
  push:
    types:
      - tags
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            installDependencies: 'sudo apt-get update -m && sudo apt-get install libconfig++-dev libevdev-dev libudev-dev'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: '${{ matrix.installDependencies }}'
      - name: Run CMake+Make
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'UnixMakefiles'
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAdditionalArgs: '-DFORCE_BUILD_HIDPP=True'
          buildWithCMakeArgs: '-- -v'
          cmakeBuildType: 'Release'
          buildDirectory: '${{ runner.workspace }}/build/'
